-- V6: Tambahkan kolom validasi bisnis ke tabel Discounts

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'MaxUsage'
)
ALTER TABLE Discounts ADD MaxUsage INT NULL;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'UsageCount'
)
ALTER TABLE Discounts ADD UsageCount INT NOT NULL DEFAULT 0;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'ExpiryDate'
)
ALTER TABLE Discounts ADD ExpiryDate DATETIME NULL;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'IsActive'
)
ALTER TABLE Discounts ADD IsActive BIT NOT NULL DEFAULT 1;
